import type { Metadata } from "next";
import { Inter as FontSans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "./header";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

const ibm = IBM_Plex_Mono({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-ibm-plex-mono",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-neutral-950 text-white ibm-plex-mono antialiased",
          ibm.variable
        )}>
          <Header />
          <div className="container py-12">
            {children}
          </div>
      </body>
    </html>
  );
}
