import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "./header";
import "@knocklabs/react/dist/index.css";
import { AppKnockProviders } from "./knock-provider";
import { SessionProvider } from "next-auth/react";

const ibm = IBM_Plex_Mono({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-ibm-plex-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-neutral-950 text-white ibm-plex-mono antialiased",
          ibm.variable
        )}>
            <SessionProvider>
              <AppKnockProviders>
                <Header />
                <div className="container py-12">
                  {children}
                </div>
              </AppKnockProviders>
            </SessionProvider>
      </body>
    </html>
  );
}
